import {StyleSheet, Dimensions} from 'react-native';
import {FONTSIZE, COLORS} from '../../utils/index';
import {RFValue, RFPercentage} from 'react-native-responsive-fontsize';
const {width, height} = Dimensions.get('screen');
import {scale, moderateScale, verticalScale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  color_stutsBar: {color: COLORS.white},
  color_textInput: {color: COLORS.gray2},
  container: {
    backgroundColor: COLORS.white,
    paddingHorizontal: RFValue(15),
    paddingTop: RFValue(25),
    flex: 1,
  },
  containerHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    marginBottom: verticalScale(24),
  },
  header: {
    width: '100%',
    color: COLORS.mainBlack,
    fontSize: FONTSIZE.xxlarge,
    fontWeight: '500',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Cairo',
  },
  viewIcon: {
    width: scale(32),
    height: scale(32),
    borderColor: COLORS.mainBlack,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(16),
    marginRight: -width * 0.09,
  },
  text: {
    color: COLORS.mainBlack,
    fontSize: FONTSIZE.medium,
    fontWeight: '400',
    marginTop: verticalScale(12),
    fontFamily: 'Cairo',
  },
  dropdown: {
    backgroundColor: COLORS.white,
    padding: width * 0.01111,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: RFValue(8),
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: verticalScale(20),
    },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 3,
    borderColor: COLORS.white,
    borderWidth: 1,
    marginTop: verticalScale(6),
  },
  dropdownHeader: {
    fontSize: FONTSIZE.large,
    color: COLORS.mainBlack,
    fontFamily: 'Cairo',
  },
  dropDownContainerStyle: {
    backgroundColor: COLORS.white,
    padding: width * 0.01111,
    borderRadius: RFValue(8),
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: verticalScale(20),
    },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 3,
    borderColor: COLORS.white,
    borderWidth: 1,
  },
  viewInput: {
    width: '100%',
    height: scale(48),
    backgroundColor: COLORS.white,
    padding: width * 0.01111,
    borderRadius: RFValue(8),
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: verticalScale(20),
    },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 2,
    marginTop: verticalScale(6),
  },
  insideTextInput: {
    color: COLORS.mainBlack,
    textAlign: 'right',
    fontSize: FONTSIZE.medium,
    fontFamily: 'Cairo',
  },
  extraView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(20),
    justifyContent: 'space-between',
  },
  extraText: {
    fontSize: FONTSIZE.medium,
    color: COLORS.gray2,
    fontWeight: '400',
    width: '58%',
    fontFamily: 'Cairo',
  },
  changeInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  changeInputView: {
    width: '45%',
  },
  viewTimes: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  containerTimes: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(10),
    justifyContent: 'space-between',
  },
  camera: {
    width: scale(25),
    height: scale(25),
    tintColor: COLORS.mainBlue,
    alignSelf: 'flex-end',
  },
  viewCamera: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: scale(10),
  },
  containerImgs: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingTop: scale(30),
  },

  imgMap: {
    width: scale(160),
    height: scale(180),
    paddingTop: scale(10),
    paddingLeft: scale(15),
  },
  close: {
    width: scale(15),
    height: scale(15),
  },
  viewBtn: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    height: RFValue(48),
    backgroundColor: '#3A82F8',
    borderRadius: RFValue(8),
    marginTop: RFValue(30),
    alignSelf: 'center',
    paddingHorizontal: scale(10),
    marginBottom: verticalScale(40),
  },
  btnText: {
    fontSize: FONTSIZE.xlarge,
    color: COLORS.white,
    fontFamily: 'Cairo',
  },
  changeViewTimes: {
    width: width * 0.2,
    marginLeft: scale(10),
    justifyContent: 'center',
    alignItems: 'center',
    height: scale(48),
    backgroundColor: COLORS.white,
    borderRadius: RFValue(8),
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: verticalScale(20),
    },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 2,
  },
  center: {
    width: '100%',
    height: '100%',
    textAlign: 'center',
    fontSize: 12,
    fontFamily: 'Cairo',
    alignItems: 'center',
    justifyContent: 'center',
    color: COLORS.mainBlack,
  },
});

export default styles;
