import {StyleSheet, Dimensions} from 'react-native';
import {FONTSIZE, COLORS} from '../../utils/fonts.util';

import {RFValue, RFPercentage} from 'react-native-responsive-fontsize';
const {width, height} = Dimensions.get('screen');
import {scale, moderateScale, verticalScale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  color_stutsBar: {color: COLORS.white},
  color_textInput: {color: COLORS.gray2},
  bottn_back: {color: COLORS.mainBlack},

  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    paddingHorizontal: RFValue(15),
    paddingTop: RFValue(25),
  },
  containerHeader: {
    flexDirection: 'row',
    width: width,
    alignItems: 'center',
  },
  header: {
    width: width * 0.8,
    height: width * 0.0888,
    lineHeight: width * 0.1023,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  heading2: {
    marginTop: RFValue(10),
    color: COLORS.mainBlack,
  },
  text_header: {
    fontSize: FONTSIZE.xxlarge,
    color: COLORS.mainBlack,
    textAlign: 'center',
    fontWeight: 'bold',
    marginRight: RFValue(20),
  },
  IconView: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: width * 0.01111,
    width: width * 0.0888,
    height: width * 0.0888,
    backgroundColor: COLORS.white,
    marginRight: RFValue(2),
    borderRadius: RFValue(8),
    shadowOffset: {
      width: width * 0.0111,
      height: width * 0.0111,
    },
    elevation: width * 0.0166,
    flexDirection: 'row',
  },
  WelcomeText: {
    fontWeight: '400',
    fontSize: FONTSIZE.large,
    color: COLORS.mainBlue,
    marginTop: RFValue(15),
    marginLeft: RFValue(15),
  },
  NameOfInput: {
    height: width * 0.07222,
    marginLeft: width * 0.7805,
    marginTop: -width * 0.028,
    fontSize: FONTSIZE.medium,
    fontWeight: '400',
    lineHeight: width * 0.07288,
    textAlign: 'left',
    color: COLORS.mainBlack,
  },
  ViewInput: {
    width: width * 0.9,
    height: height < 600 ? RFValue(50) : RFValue(40),
    backgroundColor: COLORS.white,
    borderRadius: RFValue(8),
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: COLORS.mainBlack,
    shadowOpacity: 0.5,
    alignSelf: 'center',
    shadowOffset: {
      width: scale(10),
      height: verticalScale(10),
    },
    elevation: 5,
    marginTop: height * 0.01,
  },
  inputStyle: {
    width: width * 0.77,
    color: COLORS.gray2,
    fontSize: FONTSIZE.xlarge,
    justifyContent: 'center',
    paddingHorizontal: RFValue(2.5),
    borderBottomLeftRadius: RFValue(8),
  },
  insideTextInput: {
    color: COLORS.black,
    fontSize: RFPercentage(2),
    textAlign: 'right',
    marginLeft: RFValue(2),
  },
  inputStyle_userName: {
    width: width * 0.9,
    color: COLORS.gray2,
    fontSize: FONTSIZE.xlarge,
    justifyContent: 'center',
    paddingHorizontal: RFValue(10),
    borderRadius: RFValue(8),
  },
  container_icons: {
    width: width * 0.13,
    height: height < 600 ? RFValue(50) : RFValue(40),
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomRightRadius: RFValue(8),
    borderTopRightRadius: RFValue(8),
  },
  button: {
    width: width * 0.9,
    height: height < 600 ? RFValue(48) : RFValue(37),
    backgroundColor: COLORS.mainBlue,
    borderRadius: RFValue(8),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: RFValue(28),
    alignSelf: 'center',
  },
  btnVisitor: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.mainBlue,
    borderWidth: moderateScale(1),
    marginTop: RFValue(35),
  },
  btnTextVisitor: {
    color: COLORS.mainBlue,
  },
  viewIconLogin: {
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: RFValue(15),
  },
  buttonText: {
    width: width * 0.1972,
    height: width * 0.0722,
    fontSize: FONTSIZE.medium,
    lineHeight: width * 0.0722,
    textAlign: 'right',
    color: COLORS.white,
    fontWeight: '500',
  },
  SocialText: {
    marginTop: width * 0.05,
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: FONTSIZE.smaller,
    lineHeight: width * 0.0527,
    textAlign: 'center',
    color: COLORS.black,
    paddingHorizontal: RFValue(10),
  },
  viewIcon: {
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    width: width * 0.32,
    // backgroundColor:"#f0f",
    justifyContent: 'space-between',
    marginTop: RFValue(25),
  },
  container_soical_icons: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    width: width * 0.13,
    height: height < 600 ? RFValue(40) : RFValue(30),
    shadowColor: COLORS.mainBlack,
    borderRadius: RFValue(5),
    shadowOffset: {
      width: scale(10),
      height: verticalScale(10),
    },
    elevation: 0.5,
  },
  textIcon: {
    color: COLORS.mainBlue,
    textAlign: 'center',
    fontSize: FONTSIZE.smaller,
    fontWeight: 'bold',
  },
  textIconLogin: {
    marginLeft: RFValue(13),
    color: COLORS.mainBlack,
  },
});

export default styles;
