import {StyleSheet, Dimensions} from 'react-native';
import {FONTSIZE, COLORS} from '../../utils/index';
import {RFValue, RFPercentage} from 'react-native-responsive-fontsize';
const {width, height} = Dimensions.get('screen');
import {scale, moderateScale, verticalScale} from 'react-native-size-matters';
const styles = StyleSheet.create({
  containerStyle: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  headerStyle: {
    height: height * 0.0888,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: height * 0.01,
    alignItems: 'center',
    marginHorizontal: width * 0.0555,
  },
  headerTextStyle: {
    color: COLORS.mainBlack,
    fontSize: FONTSIZE.xxlarge,
    fontFamily: 'Cairo',
    fontWeight: '500',
  },
  tabStyle: {
    backgroundColor: COLORS.white,
    width: 'auto',
  },
  containerStyle4: {
    paddingHorizontal: width * 0.04444,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textStyle: {
    width: width * 0.45277,
    height: height * 0.0444,
    marginRight: width * 0.06388,
    fontSize: FONTSIZE.large,
    lineHeight: height * 0.0444,
    fontWeight: '400',
    color: COLORS.gray1,
    fontFamily: 'Cairo',
  },
  textStyle2: {
    width: width * 0.24166,
    height: height * 0.03256,
    marginLeft: width * 0.1972,
    color: COLORS.gray2,
    marginTop: height * 0.01184,
    fontWeight: '400',
  },
  image2: {
    width: width * 0.39444,
    height: height * 0.1539,
    borderRadius: width * 0.02222,
    marginLeft: width * 0.016667,
    marginTop: height * 0.0222,
  },
  text2: {
    color: COLORS.gray4,
    fontSize: FONTSIZE.small,
    lineHeight: height * 0.0281,
    width: width * 0.1888,
    height: height * 0.02517,
    fontFamily: 'Cairo',
  },
  text3: {
    width: width * 0.30833,
    height: height * 0.04146,
    marginTop: height * 0.03405,
    fontSize: FONTSIZE.smaller,
    color: COLORS.mainBlack,
    lineHeight: height * 0.03405,
    fontFamily: 'Cairo',
  },
  image: {
    width: width * 0.06666,
    height: width * 0.06666,
    borderRadius: width * 0.03333,
    marginTop: height * 0.01184,
  },
  text: {
    width: width * 0.2416,
    height: height * 0.03552,
    marginTop: height * 0.01776,
    marginLeft: width * 0.0111,
    color: COLORS.mainBlack,
  },
  star: {
    width: width * 0.02777,
    height: width * 0.02777,
  },
  priceText: {
    width: width * 0.18611,
    height: height * 0.05476,
    marginTop: height * 0.06956,
    lineHeight: height * 0.05476,
    fontSize: FONTSIZE.xlarge,
    color: COLORS.mainBlue,
    fontFamily: 'Cairo',
  },
  reservationButtonStyle: {
    width: width * 0.1666,
    height: height * 0.05,
    borderRadius: RFValue(8),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.mainBlue,
  },
  heart: {
    marginLeft: width * 0.277,
    marginTop: scale(10),
  },
  textStyle3: {
    fontSize: FONTSIZE.medium,
    lineHeight: width * 0.07222,
    color: COLORS.white,
    textAlign: 'center',
    fontFamily: 'Cairo',
  },
  containerStyle3: {
    padding: width * 0.01388,
  },
  imageStyle2: {
    width: width * 0.9111,
    alignSelf: 'center',
    height: height * 0.28567,
    marginTop: height * 0.0222,
    borderTopRightRadius: width * 0.02222,
    borderTopLeftRadius: width * 0.02222,
  },
  containerStyle5: {
    marginTop: height * 0.02,
    justifyContent: 'space-between',
  },
  servisTextNameStyle: {
    color: COLORS.mainBlack,
  },
  priceTextStyle: {
    color: COLORS.mainBlue,
    fontSize: FONTSIZE.xlarge,
    width: width * 0.1888,
    marginLeft: width * 0.73333,
    textAlign: 'right',
    lineHeight: width * 0.1027,
    marginTop: -height * 0.029603,
    fontFamily: 'Cairo',
  },
  containerStyle6: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profilePhotoStyle: {
    width: width * 0.06667,
    height: height * 0.03554,
    borderRadius: width * 0.03333,
  },
  designerTextStyle: {
    fontSize: FONTSIZE.medium,
    color: COLORS.mainBlack,
    marginLeft: width * 0.02777,
    fontFamily: 'Cairo',
  },
  jobTitleStyle: {
    color: COLORS.gray2,
    fontSize: FONTSIZE.smaller,
    width: width * 0.225,
    marginLeft: scale(10),
    fontFamily: 'Cairo',
  },
  btnStyle: {
    width: width * 0.3977,
    height: height * 0.28419,
    alignSelf: 'center',
    marginLeft: width * 0.058333,
  },
  textStyle8: {
    fontSize: FONTSIZE.smaller,
    textAlign: 'center',
    color: COLORS.mainBlack,
    fontFamily: 'Cairo',
  },
  viewContainer: {
    width: width * 0.3977,
    height: height * 0.053285,
    borderTopLeftRadius: width * 0.02777,
    borderTopRightRadius: width * 0.02777,
    backgroundColor: 'rgba(255,255,255,0.8)',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: verticalScale(30),
  },
  filter: {
    marginLeft: -width * 0.125,
    marginTop: height * 0.01184,
  },
  favoriteButtonStyle: {
    width: width * 0.08888,
    height: height * 0.047365,
    borderRadius: width * 0.0222,
    backgroundColor: 'rgba(255,255,255,.5)',
    position: 'absolute',
    marginTop: height * 0.03552,
    marginLeft: width * 0.80222,
    alignItems: 'center',
    justifyContent: 'center',
  },
  galleryImg: {
    width: '100%',
  },
});
export default styles;
