import {StyleSheet, Dimensions} from 'react-native';
import {FONTSIZE, COLORS} from '../../utils/index';
import {RFValue, RFPercentage} from 'react-native-responsive-fontsize';
const {width, height} = Dimensions.get('screen');
import {scale, moderateScale, verticalScale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  color_stutsBar: {color: COLORS.white},
  color_textInput: {color: COLORS.gray2},
  color_Heart: {color: COLORS.red},
  color_black: {color: COLORS.mainBlack},

  container: {
    backgroundColor: COLORS.white,
    paddingHorizontal: RFValue(15),
    paddingTop: RFValue(25),
    flex: 1,
  },
  containerHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  header: {
    color: COLORS.mainBlack,
    fontSize: FONTSIZE.xxlarge,
    fontWeight: '500',
    fontFamily: 'Cairo',
  },
  viewArrow: {
    width: width * 0.0888,
    height: width * 0.0888,
    backgroundColor: COLORS.white,
    padding: width * 0.01111,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: RFValue(8),
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: verticalScale(20),
    },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 2,
  },
  viewIcon: {
    width: scale(32),
    height: scale(32),
    borderColor: COLORS.mainBlack,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: scale(16),
  },
  imgBack: {
    width: '100%',
    height: height * 0.2,
    marginTop: verticalScale(25),
  },
  btnHeart: {
    alignSelf: 'flex-end',
    margin: scale(10),
    backgroundColor: 'rgba(255,255,255,.5)',
    width: width * 0.08888,
    height: height * 0.047365,
    borderRadius: width * 0.0222,
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerRate: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: verticalScale(16),
  },
  text: {
    fontSize: FONTSIZE.large,
    fontWeight: '500',
    color: COLORS.gray1,
    fontFamily: 'Cairo',
  },
  text1: {
    color: COLORS.gray2,
    marginTop: -verticalScale(5),
  },
  rating: {
    paddingVertical: verticalScale(10),
    transform: [
      {
        rotateY: '180deg',
      },
    ],
  },
  containerMiddle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: verticalScale(16),
  },
  containerUser: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  text2: {
    fontSize: FONTSIZE.medium,
    fontWeight: '400',
    color: COLORS.gray1,
    marginLeft: scale(10),
    fontFamily: 'Cairo',
  },
  textBag: {
    marginLeft: 0,
  },
  text3: {
    fontSize: FONTSIZE.smaller,
    marginTop: verticalScale(5),
    fontFamily: 'Cairo',
  },
  containerBag: {
    height: height * 0.07,
    width: width * 0.35,
    backgroundColor: COLORS.white,
    padding: width * 0.01111,
    alignItems: 'center',
    borderRadius: RFValue(8),
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 1,
    elevation: 1,
    justifyContent: 'space-around',
  },

  headerDetailService: {
    fontSize: FONTSIZE.large,
    fontWeight: '600',
    color: COLORS.gray1,
    marginTop: verticalScale(16),
    fontFamily: 'Cairo',
  },
  textDetailService: {
    fontSize: FONTSIZE.medium,
    fontWeight: '400',
    color: COLORS.gray1,
    marginTop: verticalScale(10),
    lineHeight: scale(30),
    fontFamily: 'Cairo',
  },
  viewSave: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(10),
  },
  containerSave: {
    marginBottom: verticalScale(10),
  },
  textSave: {
    fontSize: FONTSIZE.medium,
    fontWeight: '600',
    color: COLORS.gray2,
    marginTop: verticalScale(0),
    marginLeft: scale(10),
    fontFamily: 'Cairo',
  },
  timeWork: {
    width: scale(70),
    height: scale(38),
    backgroundColor: COLORS.white,
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: verticalScale(20),
    },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 2,
    marginBottom: verticalScale(15),
    marginRight: scale(10),
  },
  textDay: {
    fontSize: FONTSIZE.xlarge,
    fontWeight: '400',
    color: COLORS.gray2,
    marginVertical: verticalScale(10),
    fontFamily: 'Cairo',
  },
  containerDays: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  containerHour: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '40%',
    padding: scale(10),
  },
  choiceDay: {
    color: COLORS.mainBlue,
    fontSize: FONTSIZE.medium,
    fontWeight: '400',
    fontFamily: 'Cairo',
  },
  notChoiceDay: {
    color: COLORS.gray2,
  },
  viewHour: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textHour: {
    color: COLORS.mainBlue,
    fontSize: FONTSIZE.large,
    fontWeight: '400',
    fontFamily: 'Cairo',
  },
  textHour2: {
    marginLeft: scale(10),
    marginRight: scale(20),
  },
  viewService: {
    width: '100%',
    height: scale(40),
    backgroundColor: COLORS.white,
    borderRadius: scale(5),
    alignItems: 'center',
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: verticalScale(20),
    },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 2,
    marginVertical: verticalScale(10),
    flexDirection: 'row',
    marginBottom: verticalScale(30),
    paddingHorizontal: width * 0.03,
  },
  textService: {
    color: COLORS.black3,
    fontSize: FONTSIZE.xlarge,
    fontWeight: '400',
    marginLeft: width * 0.04,
    fontFamily: 'Cairo',
  },
  containerComment: {
    marginTop: verticalScale(20),
  },
  viewComment: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(20),
  },
  userImage: {
    width: scale(50),
    height: scale(50),
  },
  viewText: {
    marginLeft: scale(20),
  },
  flexComment: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  from: {
    color: COLORS.mainBlack,
    fontWeight: '500',
    fontSize: FONTSIZE.xlarge,
    fontFamily: 'Cairo',
  },
  all: {
    color: COLORS.gray2,
    fontWeight: '500',
    fontSize: FONTSIZE.medium,
    fontFamily: 'Cairo',
  },
  name: {
    color: COLORS.mainBlack,
    fontWeight: '500',
    fontSize: FONTSIZE.xlarge,
    fontFamily: 'Cairo',
  },
  comment: {
    color: COLORS.gray2,
    fontWeight: '500',
    fontSize: FONTSIZE.medium,
  },
  money: {
    fontSize: FONTSIZE.xxlarge,
    fontWeight: '500',
    color: COLORS.mainBlue,
    marginTop: verticalScale(20),
    fontFamily: 'Cairo',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: verticalScale(25),
  },
  viewBtn: {
    width: width * 0.65,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    height: RFValue(48),
    backgroundColor: COLORS.mainBlue,
    borderRadius: RFValue(10),
    marginTop: RFValue(30),
    alignSelf: 'center',
    paddingHorizontal: scale(10),
  },
  btnTextbook: {
    fontSize: FONTSIZE.xlarge,
    color: COLORS.white,
    fontFamily: 'Cairo',
  },
  containerDialog: {
    backgroundColor: COLORS.white,
    height: height * 0.57,
    width: width - scale(20),
    shadowColor: COLORS.mainBlack,
    shadowOpacity: 0.9,
    elevation: 2,
    shadowOffset: {
      width: 10,
      height: 10,
    },
    borderRadius: scale(10),
  },
  containerDialog2: {
    height: height * 0.5,
  },
  img: {
    alignSelf: 'center',
    marginTop: verticalScale(40),
  },
  btnClose: {
    width: width * 0.0888,
    height: width * 0.0888,
    backgroundColor: COLORS.white,
    borderRadius: RFValue(8),
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: verticalScale(20),
    },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 2,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    marginTop: -verticalScale((width * 0.0888) / 2),
  },
  imgComment: {
    width: scale(40),
    height: scale(40),
  },
  close: {
    width: scale(14),
    height: scale(14),
    tintColor: COLORS.gray4,
  },
  dialogText1: {
    fontWeight: '400',
    color: COLORS.mainBlack,
    alignSelf: 'center',
    marginTop: verticalScale(8),
    fontSize: FONTSIZE.large,
    fontFamily: 'Cairo',
  },
  dialogText2: {
    fontWeight: '400',
    color: COLORS.gray2,
    marginBottom: verticalScale(14),
  },
  btnText1: {
    fontSize: FONTSIZE.xlarge,
    color: COLORS.white,
    fontFamily: 'Cairo',
  },
  btnView1: {
    width: scale(266),
    height: RFValue(48),
    backgroundColor: COLORS.mainBlue,
    borderRadius: RFValue(8),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: RFValue(8),
    alignSelf: 'center',
  },
  btnText2: {
    color: COLORS.mainBlue,
  },
  btnView2: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.mainBlue,
    borderWidth: 1,
  },
  textDone: {
    fontSize: FONTSIZE.medium,
    fontFamily: 'Cairo',
  },
  marginTop: {
    marginTop: scale(20),
  },
  sheet: {
    height: height * 0.65,
    padding: RFValue(15),
    borderRadius: scale(10),
    paddingTop: scale(30),
  },
  containerHeaderSheet: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerSheet: {
    color: COLORS.mainBlack,
    fontSize: FONTSIZE.xxlarge,
    fontWeight: 'bold',
    width: '95%',
    textAlign: 'center',
    marginLeft: 10,
    fontFamily: 'Cairo',
  },
  imgPaymentSheet: {
    marginTop: verticalScale(60),
    alignSelf: 'center',
    marginBottom: verticalScale(48),
  },
  textInput: {
    textAlign: 'right',
    color: COLORS.mainBlack,
    height: scale(46),
    width: '100%',
    borderRadius: scale(10),
    alignItems: 'center',
    paddingHorizontal: scale(10),
    backgroundColor: COLORS.white,
    borderColor: COLORS.secondWhite,
    borderWidth: 1,
    marginTop: verticalScale(4),
    marginBottom: verticalScale(28),
  },
});

export default styles;
