// import {StyleSheet, Dimensions} from 'react-native';
// import {FONTSIZE, COLORS} from '../../utils/fonts.util';
// import {RFValue, RFPercentage} from 'react-native-responsive-fontsize';
// const {width, height} = Dimensions.get('screen');
// import {scale, moderateScale, verticalScale} from 'react-native-size-matters';
// const styles = StyleSheet.create({
//   padding: {
//     padding: scale(10),
//   },
//   containerStyle: {
//     flex: 1,
//     backgroundColor: COLORS.white,
//   },
//   headerStyle: {
//     padding: width * 0.055555,
//     alignSelf: 'center',
//     justifyContent: 'space-between',
//     flexDirection: 'row',
//   },
//   buttonIconStyle: {
//     marginLeft: 0.0555,
//     height: height * 0.0592,
//     width: width * 0.1111,
//     alignItems: 'center',
//     justifyContent: 'center',
//   },
//   ViewSearchStyle: {
//     width: width * 0.6733,
//     height: height * 0.05328,
//     borderWidth: 0.5,
//     borderRadius: RFValue(8),
//     flexDirection: 'row',
//     paddingHorizontal: 5,
//     alignItems: 'center',
//     alignSelf: 'center',
//     borderColor: COLORS.gray3,
//     shadowOffset: {
//       width: width * 0.0222,
//       height: width * 0.0222,
//     },
//     shadowColor: '#000',
//     marginHorizontal: scale(8),
//   },
//   viewSwiper: {
//     flexDirection: 'row',
//     position: 'absolute',
//     marginTop: scale(22),
//   },
//   textSwiper: {
//     width: scale(60),
//     height: scale(45),
//     fontSize: FONTSIZE.large * 1.7,
//     lineHeight: verticalScale(45),
//     marginLeft: scale(150),
//     marginTop: verticalScale(15),
//     color: COLORS.white,
//   },
//   textInputStyle: {
//     width: width * 0.4833,
//     height: height,
//     marginLeft: 12,
//     borderRadius: RFValue(8),
//     fontSize: FONTSIZE.medium,
//     color: COLORS.mainBlack,
//   },
//   backgroundImageStyle: {
//     width: width * 0.9111,
//     height: height * 0.251626,
//     borderRadius: width * 0.02777,
//     alignSelf: 'center',
//   },
//   containerStyle2: {
//     flexDirection: 'row',
//     paddingHorizontal: verticalScale(16),
//     marginTop: verticalScale(10),
//   },
//   textStyle: {
//     width: width * 0.45277,
//     height: height * 0.0444,
//     marginRight: width * 0.06388,
//     fontSize: FONTSIZE.large,
//     lineHeight: height * 0.0444,
//     fontWeight: '400',
//     color: COLORS.gray1,
//   },
//   textStyle2: {
//     width: width * 0.24166,
//     height: height * 0.03256,
//     marginLeft: width * 0.1972,
//     color: COLORS.gray2,
//     marginTop: verticalScale(8),
//     fontWeight: '400',
//   },
//   containerStyle3: {
//     padding: 5,
//   },
//   viewItemStyle: {
//     width: width * 0.3816,
//     height: height * 0.2161,
//     borderRadius: width * 0.02777,
//   },
//   imageStyle: {
//     width: width * 0.3816,
//     height: height * 0.1746585656,
//     borderTopRightRadius: width * 0.02777,
//     borderTopLeftRadius: width * 0.02777,
//   },
//   containerStyle4: {
//     //marginTop: -5,
//     paddingHorizontal: scale(16),
//     flexDirection: 'row',
//     marginBottom: -verticalScale(10),
//   },
//   imageStyle2: {
//     width: width * 0.9111,
//     alignSelf: 'center',
//     height: height * 0.28567,
//     marginTop: 15,
//     borderTopRightRadius: scale(8),
//     borderTopLeftRadius: scale(8),
//   },
//   containerStyle5: {
//     marginTop: width * 0.0111,
//     width: width * 0.49444,
//     height: height * 0.041444,
//     marginLeft: width * 0.05833,
//   },
//   servisTextNameStyle: {},
//   priceTextStyle: {
//     color: COLORS.mainBlue,
//     fontSize: FONTSIZE.xlarge,
//     width: width * 0.1888,
//     height: height * 0.054796,
//     marginLeft: width * 0.73333,
//     textAlign: 'right',
//     lineHeight: width * 0.1027,
//     marginTop: -verticalScale(20),
//   },
//   containerStyle6: {
//     flexDirection: 'row',
//     alignItems: 'center',
//     width: width * 0.3888,
//     height: height * 0.03848,
//     marginLeft: width * 0.05833,
//   },
//   profilePhotoStyle: {
//     width: width * 0.06667,
//     height: height * 0.03554,
//     borderRadius: width * 0.03333,
//   },
//   designerTextStyle: {
//     fontSize: FONTSIZE.medium,
//     color: COLORS.mainBlack,
//     marginLeft: scale(10),
//   },
//   jobTitleStyle: {
//     color: COLORS.gray2,
//     fontSize: FONTSIZE.smaller,
//     //marginTop: 8,
//     width: width * 0.225,
//     height: height * 0.0355,
//     //paddingHorizontal: 20,
//     marginLeft: width * 0.06833,
//   },
//   reservationButtonStyle: {
//     width: width * 0.1666,
//     height: height * 0.05,
//     borderRadius: RFValue(8),
//     marginLeft: width * 0.4544,
//     alignItems: 'center',
//     justifyContent: 'center',
//     backgroundColor: COLORS.blue,
//   },
//   textStyle3: {
//     fontSize: FONTSIZE.medium,
//     lineHeight: width * 0.07222,
//     color: COLORS.white,
//   },
//   textStyle4: {
//     width: width * 0.2583,
//     height: height * 0.1465,
//     fontWeight: '700',
//     fontSize: scale(44),
//     lineHeight: height * 0.1184,
//     color: COLORS.red,
//   },
//   textStyle5: {
//     fontSize: FONTSIZE.large * 1.9,
//     lineHeight: height * 0.0666,
//     width: width * 0.1388,
//     height: height * 0.0666,
//     position: 'absolute',
//     marginTop: height * 0.1184,
//     marginLeft: width * 0.5555,
//     color: COLORS.white,
//   },
//   textStyle6: {
//     fontSize: FONTSIZE.xxlarge,
//     lineHeight: height * 0.0444,
//     width: width * 0.5555,
//     height: height * 0.0444,
//     position: 'absolute',
//     marginTop: height * 0.1776,
//     marginLeft: width * 0.375,
//     color: COLORS.white,
//   },
//   textStyle7: {
//     textAlign: 'center',
//     lineHeight: width * 0.0722,
//     marginTop: verticalScale(2),
//     fontSize: FONTSIZE.medium,
//     color: 'gray',
//   },
// });
// export default styles;

import {StyleSheet, Dimensions} from 'react-native';
import {FONTSIZE, COLORS} from '../../utils/index';
import {RFValue, RFPercentage} from 'react-native-responsive-fontsize';
const {width, height} = Dimensions.get('screen');
import {scale, moderateScale, verticalScale} from 'react-native-size-matters';
const styles = StyleSheet.create({
  containerStyle: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  headerStyle: {
    padding: width * 0.0555,
    alignSelf: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  buttonIconStyle: {
    marginLeft: width * 0.0555,
    height: height * 0.0592,
    width: width * 0.1111,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconStyle: {
    fontSize: FONTSIZE.xxlarge,
    //color: COLORS.mainBlue,
  },
  ViewSearchStyle: {
    width: width * 0.6733,
    height: height * 0.05328,
    borderWidth: 0.5,
    borderRadius: RFValue(8),
    flexDirection: 'row',
    paddingHorizontal: width * 0.02,
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: COLORS.gray3,
    shadowOffset: {
      width: width * 0.0222,
      height: width * 0.0222,
    },
    shadowColor: COLORS.black,
  },
  textSearch: {
    color: COLORS.gray2,
    fontSize: FONTSIZE.medium,
    marginLeft: scale(15),
    fontFamily: 'Cairo',
  },
  backgroundImageStyle: {
    width: width * 0.92,
    height: height * 0.251626,
    //marginTop: height * 0.01368,
    borderRadius: RFValue(10),
    alignSelf: 'center',

  },
  header_image:{
    alignSelf:'flex-end',
    height: height * 0.251626,
    width : width*0.63  },
  containerStyle2: {
    flexDirection: 'row',
    paddingHorizontal: width * 0.0444,
    marginTop: height * 0.014801,
    justifyContent: 'space-between',
  },
  textStyle: {
    width: width * 0.45277,
    marginRight: width * 0.06388,
    fontSize: FONTSIZE.large,
    lineHeight: height * 0.0444,
    fontWeight: '400',
    color: COLORS.gray1,
    fontFamily: 'Cairo',
  },
  textStyle2: {
    height: height * 0.03256,
    color: COLORS.gray2,
    marginTop: height * 0.01184,
    fontWeight: '400',
    fontFamily: 'Cairo',
    fontSize:scale(12)
  },
  containerStyle3: {
    paddingVertical: width * 0.01388,
    paddingHorizontal:RFValue(4)
  },
  imageStyle: {
    width: width * 0.3816,
    height: height * 0.1746585656,
    borderTopRightRadius: RFValue(10),
    borderTopLeftRadius: RFValue(10),
  },
  containerStyle4: {
    paddingHorizontal: width * 0.04444,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  imageStyle2: {
    width: width * 0.9111,
    alignSelf: 'center',
    height: height * 0.28567,
    marginTop: height * 0.0222,
    borderTopRightRadius: width * 0.02222,
    borderTopLeftRadius: width * 0.02222,
  },
  containerStyle5: {
    marginTop: height * 0.02,
    justifyContent: 'space-between',
  },
  servisTextNameStyle: {
    color: COLORS.mainBlack,
    fontFamily: 'Cairo',
  },
  priceTextStyle: {
    color: COLORS.mainBlue,
    fontSize: FONTSIZE.xlarge,
    width: width * 0.1888,
    marginLeft: width * 0.73333,
    textAlign: 'right',
    lineHeight: width * 0.1027,
    marginTop: -height * 0.029603,
    fontFamily: 'Cairo',
  },
  containerStyle6: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profilePhotoStyle: {
    width: width * 0.06667,
    height: height * 0.03554,
    borderRadius: width * 0.03333,
  },
  designerTextStyle: {
    fontSize: FONTSIZE.medium,
    color: COLORS.mainBlack,
    marginLeft: width * 0.02777,
    fontFamily: 'Cairo',
  },
  jobTitleStyle: {
    color: COLORS.gray2,
    fontSize: FONTSIZE.smaller,
    width: width * 0.225,
    marginLeft: scale(10),
    fontFamily: 'Cairo',
  },
  reservationButtonStyle: {
    width: width * 0.1666,
    height: height * 0.05,
    borderRadius: RFValue(8),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.mainBlue,
  },
  textStyle3: {
    fontSize: FONTSIZE.medium,
    lineHeight: width * 0.07222,
    color: COLORS.white,
    textAlign: 'center',
    fontFamily: 'Cairo',
  },
  textStyle4: {
    height: height * 0.1465,
    fontWeight: '700',
    fontSize: scale(48),
    lineHeight: height * 0.1184,
    color: COLORS.red,
    marginLeft: scale(10),
    fontFamily: 'Cairo',
  },
  textStyle5: {
    fontSize: scale(24),
    lineHeight: height * 0.0666,
    height: height * 0.0666,
    position: 'absolute',
    marginTop: height * 0.085,
    marginLeft: width * 0.5555,
    color: COLORS.white,
    fontFamily: 'Cairo',
    fontWeight:"400"
  },
  textStyle6: {
    fontSize: scale(22),
    fontFamily: 'Cairo',
    lineHeight: height * 0.0444,
    width: width * 0.5555,
    // height: height * 0.0444,
    position: 'absolute',
    marginTop: height * 0.1556,
    marginLeft: width * 0.375,
    color: COLORS.white,
  },
  textStyle7: {
    textAlign: 'center',
    lineHeight: width * 0.0722,
    marginTop: height * 0.00296,
    fontSize: FONTSIZE.medium,
    color: COLORS.mainBlack,
    fontFamily: 'Cairo',
    fontWeight:"400"
  },
  textStyle8: {
    fontSize: FONTSIZE.smaller,
    textAlign: 'center',
    color: COLORS.mainBlack,
    fontFamily: 'Cairo',
  },
  viewContainer: {
    width: width * 0.3977,
    height: height * 0.053285,
    borderTopLeftRadius: width * 0.02777,
    borderTopRightRadius: width * 0.02777,
    backgroundColor: 'rgba(255,255,255,0.8)',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: verticalScale(30),
 

  },
  btnStyle: {
    width: width * 0.3977,
    height: height * 0.28419,
    alignSelf: 'center',
    marginLeft: width * 0.058333,
  },

  priceText: {
    width: width * 0.18611,
    height: height * 0.05476,
    marginTop: height * 0.06956,
    lineHeight: height * 0.05476,
    fontSize: FONTSIZE.xlarge,
    color: COLORS.mainBlue,
    fontFamily: 'Cairo',
  },
  star: {
    width: width * 0.02,
    height: width * 0.02777,
  },
  text: {
    width: width * 0.2416,
    height: height * 0.03552,
    marginTop: height * 0.01776,
    marginLeft: width * 0.0111,
    color: COLORS.mainBlack,
    fontSize: FONTSIZE.smaller,
  },
  image: {
    width: width * 0.06666,
    height: width * 0.06666,
    borderRadius: width * 0.03333,
    marginTop: height * 0.01184,
  },
  text2: {
    color: COLORS.gray4,
    fontSize: FONTSIZE.smaller,
    lineHeight: height * 0.0281,
    width: width * 0.1888,
    height: height * 0.02517,
    fontFamily: 'Cairo',
  },
  text3: {
    width: width * 0.30833,
    height: height * 0.04146,
    marginTop: height * 0.03405,
    fontSize: FONTSIZE.smaller,
    color: COLORS.mainBlack,
    lineHeight: height * 0.03405,
    fontFamily: 'Cairo',
  },
  image2: {
    width: width * 0.39444,
    height: height * 0.1539,
    borderRadius: width * 0.02222,
    marginLeft: width * 0.016667,
    marginTop: height * 0.0222,
  },
  text4: {
    // height: height * 0.0666,
    fontSize: scale(24),
    // lineHeight: height * 0.0666,
    fontWeight: '600',
    marginLeft: width * 0.41666,
    marginTop: height * 0.0222,
    color: COLORS.white,
    fontFamily: 'Cairo',
    marginRight:10
  },
  view: {
    flexDirection: 'row',
    position: 'absolute',
    marginTop: RFValue(8),
    // justifyContent:"flex-end",
    // alignItems:"center",
    alignSelf:"flex-end",
    // marginRight:RFValue(15),
    // backgroundColor:"#f00"
  },
  favoriteButtonStyle: {
    width: width * 0.08888,
    height: height * 0.047365,
    borderRadius: width * 0.0222,
    backgroundColor: 'rgba(255,255,255,.5)',
    position: 'absolute',
    marginTop: height * 0.03552,
    marginLeft: width * 0.80222,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heart: {
    marginLeft: width * 0.277,
    marginTop: scale(10),
  },
  galleryImg: {
    width: '100%',
  },
});
export default styles;
