import {StyleSheet, Dimensions} from 'react-native';
import {scale} from 'react-native-size-matters';
import {FONTSIZE, COLORS} from '../../utils/fonts.util';
const {width, height} = Dimensions.get('screen');
const styles = StyleSheet.create({
  containerStyle: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  viewStyle: {
    width: '100%',
    height: height * 0.168,
    backgroundColor: COLORS.mainBlack,
    borderBottomRightRadius: width * 0.02777,
    borderBottomLeftRadius: width * 0.02777,
  },
  viewImageStyle: {
    width: width * 0.26111,
    height: width * 0.26111,
    marginTop: height * 0.099168,
    borderRadius: width * 0.1305,
    position: 'absolute',
    borderWidth: 1,
    borderColor: COLORS.yellow,
    alignSelf: 'center',
    backgroundColor: COLORS.gray2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  welcomeTextStyle: {
    width: width * 0.2055,
    height: height * 0.054765,
    alignSelf: 'center',
    marginTop: height * 0.08,
    fontSize: FONTSIZE.xxlarge,
    lineHeight: height * 0.054765,
    color: COLORS.mainBlue,
    fontFamily: 'Cairo',
  },
  textStyle: {
    width: width * 0.605556,
    height: height * 0.03256,
    marginTop: width * 0.0111,
    textAlign: 'center',
    alignSelf: 'center',
    fontSize: FONTSIZE.smaller,
    lineHeight: height * 0.03256,
    color: COLORS.gray4,
    fontFamily: 'Cairo',
  },
  loginButtonStyle: {
    width: width * 0.2722,
    height: height * 0.06216,
    marginTop: height * 0.01184,
    padding: width * 0.02222,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: COLORS.yellow,
    borderRadius: width * 0.02222,
  },
  loginTextStyle: {
    fontSize: FONTSIZE.smaller,
    lineHeight: height * 0.0384116,
    color: COLORS.white,
    fontFamily: 'Cairo',
  },
  containerStyle2: {
    flexDirection: 'row',
    marginTop: height * 0.02664,
    marginLeft: width * 0.0333,
    alignItems: 'center',
  },
  iconStyle: {
    width: width * 0.062777,
    color: COLORS.gray2,
    fontSize: FONTSIZE.xxlarge,
    fontFamily: 'Cairo',
  },
  textNameStyle: {
    fontSize: FONTSIZE.xlarge,
    lineHeight: height * 0.0444,
    color: COLORS.mainBlack,
    marginLeft: scale(20),
    fontFamily: 'Cairo',
  },
  lineStyle: {
    width: '80%',
    marginTop: 12,
    alignSelf: 'center',
    borderWidth: 0.5,
    borderColor: COLORS.yellow2,
  },
  imageStyle: {
    width: width * 0.2611,
    height: width * 0.2611,
    borderRadius: height * 0.1305,
  },
  containerStyle3: {
    borderTopLeftRadius: width * 0.0833,
    borderTopRightRadius: width * 0.0833,
    height: height * 0.2,
    padding: scale(20),
  },
  viewStyle2: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: height * 0.04,
  },
  textStyle2: {
    fontSize: FONTSIZE.xlarge,
    fontWeight: '500',
    color: COLORS.black,
    fontFamily: 'Cairo',
  },
  viewStyle3: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: width * 0.05555,
    alignItems: 'center',
  },
  buttonStyle: {
    height: height * 0.06,
    width: '45%',
    backgroundColor: COLORS.mainBlue,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 0.0277,
  },
  textStyle3: {
    color: COLORS.white,
    fontSize: FONTSIZE.xlarge,
    fontFamily: 'Cairo',
  },
});
export default styles;
