import {StyleSheet, Dimensions} from 'react-native';
import {FONTSIZE, COLORS} from '../../utils/fonts.util';
import {RFValue, RFPercentage} from 'react-native-responsive-fontsize';
const {width, height} = Dimensions.get('screen');
import {scale, moderateScale, verticalScale} from 'react-native-size-matters';
const styles = StyleSheet.create({
  containerStyle: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  headerStyle: {
    padding: 20,
    alignSelf: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  buttonIconStyle: {
    marginLeft: verticalScale(20),
    height: scale(40),
    width: scale(40),
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconStyle: {
    color: COLORS.mainBlue,
  },
  ViewSearchStyle: {
    width: width * 0.7333,
    height: height * 0.05625,
    borderWidth: 0.5,
    borderRadius: RFValue(8),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(10),
    borderColor: COLORS.gray3,
    shadowOffset: {
      width: width * 0.0111,
      height: width * 0.0111,
    },
    justifyContent: 'space-between',
  },
  textSearch: {
    color: COLORS.mainBlack,
    marginLeft: 8,
    borderRadius: RFValue(8),
    fontFamily: 'Cairo',
  },
  textInputStyle: {
    flexDirection: 'row',
  },
  jobTitleStyle: {
    color: COLORS.gray2,
    fontSize: FONTSIZE.smaller,
    marginTop: 5,
    width: width * 0.225,
    height: height * 0.0355,
    marginLeft: width * 0.06933,
    fontFamily: 'Cairo',
  },
  deletViewStyle: {
    width: width * 0.14146,
    height: height * 0.05,
    borderRadius: RFValue(8),
    backgroundColor: '#FFEAEA',
    marginLeft: width * 0.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textStyle: {
    fontSize: FONTSIZE.smaller,
    lineHeight: width * 0.07222,
    color: COLORS.mainBlack,
    fontFamily: 'Cairo',
    fontWeight: '500',
  },
  reservationButtonStyle: {
    width: width * 0.1666,
    height: height * 0.05,
    borderRadius: RFValue(8),
    marginLeft: width * 0.4544,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.blue,
  },
  waitViewStyle: {
    width: width * 0.4694,
    height: height * 0.05,
    marginLeft: width * 0.15,
    borderRadius: RFValue(8),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.light,
  },
  imageStyle: {
    width: '90%',
    alignSelf: 'center',
    height: height * 0.28567,
    marginTop: verticalScale(15),
    borderTopRightRadius: 8,
    borderTopLeftRadius: 8,
  },
  containerStyle2: {
    marginTop: width * 0.0111,
    width: width * 0.49444,
    height: height * 0.041444,
    marginLeft: width * 0.05833,
  },
  servisTextNameStyle: {
    color: COLORS.mainBlack,
    fontSize: FONTSIZE.medium,
    height: height * 0.054796,
    marginTop: verticalScale(15),
    fontFamily: 'Cairo',
  },
  priceTextStyle: {
    color: COLORS.mainBlue,
    fontSize: FONTSIZE.xlarge,
    width: width * 0.1888,
    height: height * 0.054796,
    marginLeft: width * 0.73333,
    textAlign: 'right',
    lineHeight: width * 0.1027,
    marginTop: -verticalScale(20),
    fontFamily: 'Cairo',
  },
  containerStyle3: {
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.3888,
    height: height * 0.03848,
    marginLeft: width * 0.05833,
  },
  designerTextStyle: {
    fontSize: FONTSIZE.medium,
    color: COLORS.mainBlack,
    marginLeft: scale(10),
    fontFamily: 'Cairo',
  },
  profilePhotoStyle: {
    width: width * 0.06667,
    height: height * 0.03554,
    borderRadius: width * 0.03333,
  },
  empty: {
    flex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textEmpty: {
    marginTop: verticalScale(10),
    fontWeight: '400',
    color: COLORS.mainBlack,
    fontSize: FONTSIZE.large,
    fontFamily: 'Cairo',
  },
});
export default styles;

// ViewSearchStyle: {
//   width: width * 0.7333,
//   height: height * 0.05625,
//   borderWidth: 0.5,
//   borderRadius: RFValue(8),
//   flexDirection: 'row',
//   alignItems: 'center',
//   alignSelf: 'center',
//   paddingHorizontal: scale(10),
//   borderColor: COLORS.gray3,
//   shadowOffset: {
//     width: width * 0.0111,
//     height: width * 0.0111,
//   },
// },
// textInputStyle: {
//   width: width * 0.2833,
//   height: height,
//   marginLeft: 8,
//   borderRadius: RFValue(8),
//   color: COLORS.mainBlack,
// },
